### ISSUE TITLE
Persistent Mode

### ISSUE THREAD

**Issue by kuronari** [animebook/animebook.github.io#10]
Would be nice to have a persistent player without losing the files when refreshing the page.

**Comment by chalkmurex** [comment]
Would be nice since I have to refresh the page whenever yomichan bugs out and stops working, but I don't think it's possible? A website can't really keep a hold of a file on your hard drive after you refresh.

**Comment by kuronari** [comment]
That's sad. There's no way around it? Like storing locally or something?

**Comment by chalkmurex** [comment]
Not that I know of. I looked around a bit and most SO answers say it's impossible e.g. https://stackoverflow.com/questions/19119040/how-do-i-save-and-restore-a-file-object-in-local-storage
which suggests you'd need to read the entire file (in this case video) into memory and put it into local storage to do it, which I don't want to do with ~1GB files. And I can't store only the file path and use that to load the video across refreshes, since it'd be pretty scary if a website could reach out to your hard drive without permission and grab a file. It's kinda just the limitation of not doing something like voracious app which is a desktop app.

I'll close for now, but I might revisit later if I find out you can do it.

**Comment by kuronari** [comment]
Appreciate it.
