### ISSUE TITLE
Using arrow keys to navigate subs/time?

### ISSUE THREAD

**Issue by shadiow6** [animebook/animebook.github.io#14]
Sorry if this is a noob request, maybe I am missing something. 
So it seems that all the 4 arrow keys are for moving backward and forward around  ~5 seconds. 
May I suggest using Left/Right for navigating time on the seekbar and **Up/Down for navigating subtitles** (similar to the old Fluentcard site) instead? It seems more intuitive this way according to the UI/site layout. Also, navigating via subs would be useful for more accurate timing for taking screenshots and recoding audio for making anki cards instead of clicking with mouse.

**Comment by chalkmurex** [comment]
The arrow keys still navigate from subtitle to subtitle, but I put a ~6 second limit on how far it can jump, so if the sub you're trying to jump to is say, 90 seconds away, it'll do a 6 second time seek instead of jumping all the way to it.

When I wrote it, I considered what you're suggesting with assigning the subseek and timeseek functions to the up/down and left/right arrows separately, but ultimately decided against it since I didn't like thinking about which set of arrow keys I needed to push. Mostly a preference at this point, but I'm not too interested in changing it.
