### ISSUE TITLE
Desync with mp3 files

### ISSUE THREAD

**Issue by sihue** [animebook/animebook.github.io#15]
I noticed that opening mp3 files with corresponding subtitle files leads to desynchronization when juping around (i.e. whenever there is a seek). This was first tested in Chrome and later confirmed in Firefox, where the effect is even more pronounced.
My (admittedly baseless) speculation is that it might have to do with lacking keyframes in mp3 files or something similar. Even removed from animebook, moving around in mp3 files seems to be an issue for browsers, esp. Firefox.
If anyone else finds themselves faced with this issue, converting the file to wav, for example, seems to be a solution.

Even though it's more of a fringe issue, animebook could at least theoretically be used for audiobooks. (Something like this existed for public domain audiobooks using a now discontinued chromium app. I forget the exact name. edit: https://youtu.be/7eWKOI-C-N8 )
Classifying this as an "issue" is a bit disingenuous, because fixing browser issues is clearly beyond the scope of this project and animebook itself does not even claim to handle audio files.
Still, I thought it may be interesting to some.

**Comment by soameshi** [comment]
I admit that video looks cool, though I don't know how you'd get timing information from audiobook text. Maybe you could get something almost not broken if you ran an aozora bunko text through alass? Not sure what that'd look like.

But yeah, nothing really to do here since I don't want to support audio. Thanks for the tip on converting to wav though. 👍
