### ISSUE TITLE
Could you add an option to have the video stop at the end of each subtitle?

### ISSUE THREAD

**Issue by xrishox** [animebook/animebook.github.io#2]
This is a feature that I use with Language Learning with Netflix and it works great. I have to pause it anyways since I have to parse it with yomichan and sometimes I stop it too late and need to go back. If there could be a feature to have it auto stop that would be great.

**Comment by lunatum** [comment]
First example video I found of this: https://www.youtube.com/watch?v=pMrWX2dlGIM. Specifically looking at the auto-pause thing that shows up in the corner and the subtitle timeline at the bottom of the screen.

Hmm, might be nice. I probably wouldn't use the feature much, but I'm not against it (especially if it's just enabled with a hotkey or something). I suppose the one time I tried to screen share fluentcards back in the day this actually would've come in handy.

**Comment by xrishox** [comment]
i'm sure as your proficiency with the language goes up then needing to pause it as much isn't really necessary, but at my level I need to pause basically at the end of every line to go through and parse the sentence. that feature would be a huge boon. it isn't absolutely necessary since I can obviously still manually pause, but that is kinda clunky and imperfect. the feature would be a nice quality of life fix.

**Comment by lunatum** [comment]
Tried implementing this for a bit, but it's a bit tricky with a web player. Might take another try at it later, but I'll leave some notes here for now,
- The video element has a timeupdate event and a  cuechange event, but both are not super accurate for detecting changes as the video is playing. timeupdate only sends an update every 0.3 seconds or so, which can make the difference between pausing at the right time or bleeding into the next line for a syllable or two. cuechange is also a bit delayed on telling you when the caption actually should have changed. I think I can make this not a huge issue by pausing intelligently in the non-voiced time in between lines, but if someone in a show is talking fast, there will be some unavoidable bleed over into the next line.
- A lot of subs are inaccurate and tell you a line's ended before the voice is actually finished, so it's probably best to pause a split second after the line ends if there's enough leeway before the next line starts. This seems to be what Language Learning with Netflix extension does (based on how the subtitle timeline at the bottom of that video pauses just a _bit_ later when there's enough non-voiced space after a line).
- Not sure how parallel captions will work with this, since you might have a subtitle timeline that has overlapping captions like this,
```
<------------ Caption A: 7 seconds long ------------------>
            <---- Caption B: 3 seconds long --->
```
In this case, caption B will end before caption A is finished, meaning I have to auto-pause at the end of B. But, that'll make it so you never hear A as a contiguous 7 second line; you'll hear like 4 seconds of it, get paused, play, and then hear the last 3 seconds of it. There's not really anything I can do about that though since the alternative is abandoning B in some way, so uhh, parallel captions will just have to suck at auto-pausing I think. Thankfully they're rare.

**Comment by lunatum** [comment]
I think I've got it working as well as I want it to at this point. Hit 'A' on your keyboard to give it a try. I also put the hotkey shortcuts in a help dialog in the app itself.

**Comment by xrishox** [comment]
Wow thank you so much! I've just tested it out and it seems to be working great! This is really helpful for me thank you!
