### ISSUE TITLE
The extension stopped working after the last update

### ISSUE THREAD

**Issue by kappitanKappa** [animebook/animebook.github.io#24]
Hey, sadly, the extension wtopped working for me following the last update.
When I press the button next to the subtitle, there are 2 possible outcomes:
1) the loading animation just goes on indefinitely
2) an error pops up saying "Failed to record flashcard. The Animebook extension may not be fully loaded yet."

Either one results in nothing happening to the flashcards.
I tried resetting to default settings, reinstalling the extension and reinstalling AnkiConnect, but none of these things helped. I was making cards yeasterday just fine, but I loaded up AnimeBook today and it just didn't work.

**Comment by soameshi** [comment]
I have not encountered (1) yet. Is it video specific? I don't mind testing with your video if it's an anime release on nyaa or something. Also what browser are you using? A screenshot might help here.

(2) I have seen before, usually due to me opening animebook in multiple tabs which overloads ffmpeg in the background and causes the extension to crash. Reloading the page will fix this, but if you just run into infinite loading after doing that there's probably something wrong going on since the last release.

In the meantime you can go back to v.0.0.5, which should still work. https://github.com/animebook/animebook.github.io/releases/tag/v0.0.5

**Comment by kappitanKappa** [comment]
I'm on Chrome, tried it with Brave as well but ran into the same issue.
(1) was an issue with all the files from the same series, (2) probably happened exactly the way you say, ended up back at (1) after refreshing.
I tried loading in a completely different anime series (downloaded from the same source, though) and that seems to have fixed the issue even for the files I had problems with.

**Comment by soameshi** [comment]
Huh, I'm glad it works now but the infinite loading is a bit worrying. It may have something to do with #19 so I might add something to make it easier to diagnose later. Let me know if it shows up again, and if it does, I can try using the series you're using to debug it.

**Comment by kappitanKappa** [comment]
In case you wanna try debugging with the show, I'm using Nichijou (ep. 3 in this very case) downloaded from Animelon. (I literally just copy the source URL from the <video> tag from the source code, it's kinda weird, but for a lot of shows, I've found the download times to be much faster than torrents)
