### ISSUE TITLE
Error: File could not be read! Code=0

### ISSUE THREAD

**Issue by SpasiboKojima** [animebook/animebook.github.io#25]
Went through 2 Seasons of one show, now trying another and having this when dropping video file:
![image](https://user-images.githubusercontent.com/34808650/109537102-931e7d80-7acf-11eb-9217-a64c3919583b.png)
And the same again when trying to add sentence to a card:
![image](https://user-images.githubusercontent.com/34808650/109537348-d4169200-7acf-11eb-9b4b-544944f4eade.png)
But the video and everything plays perfectly. Chromium with all-codecs+ from the link in README.
Video info if it helps:
```
General
Unique ID                      : 33599052631348504530378847604148122841 (0x1946F1312C6045B69680CF941149B4D9)
Complete name                  : D:\Pictures with sound\Kakegurui／ 賭ケグルイ [Live Action S02] (BDRip 1920x1080p AVC FLAC)\[Shimazu] Kakegurui／ 賭ケグルイ [Live Action S02] 第01話 (BDRip 1920x1080p AVC FLAC AC-3).mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 2.25 GiB
Duration                       : 23 min 31 s
Overall bit rate mode          : Variable
Overall bit rate               : 13.7 Mb/s
Movie name                     : [Shimazu] Kakegurui／ 賭ケグルイ [Live Action S02] 第一話 (BDRip 1920x1080p AVC FLAC)
Encoded date                   : UTC 2019-11-04 02:23:56
Writing application            : mkvmerge v38.0.0 ('The Silent Type') 64-bit
Writing library                : libebml v1.3.9 + libmatroska v1.5.2

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High 10@L5
Format settings                : CABAC / 6 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 6 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 23 min 31 s
Bit rate                       : 11.6 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.233
Stream size                    : 1.91 GiB (85%)
Title                          : [Shimazu] Kakegurui／ 賭ケグルイ [Live Action S02] 第一話 (BDRip 1920x1080p AVC FLAC)
Writing library                : x264 core 157 r2935 545de2f
Encoding settings              : cabac=1 / ref=6 / deblock=1:1:1 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=11600 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:0.60
Default                        : Yes
Forced                         : No

Audio #1
ID                             : 2
Format                         : FLAC
Format/Info                    : Free Lossless Audio Codec
Codec ID                       : A_FLAC
Duration                       : 23 min 31 s
Bit rate mode                  : Variable
Bit rate                       : 1 461 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 10.417 FPS (4608 SPF)
Bit depth                      : 24 bits
Compression mode               : Lossless
Stream size                    : 246 MiB (11%)
Title                          : FLAC [Main]
Writing library                : Lavf58.25.100
Language                       : Japanese
Default                        : No
Forced                         : No

Audio #2
ID                             : 3
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Codec ID                       : A_AC3
Duration                       : 23 min 31 s
Bit rate mode                  : Constant
Bit rate                       : 640 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Compression mode               : Lossy
Stream size                    : 108 MiB (5%)
Title                          : AC-3 [Documentary]
Language                       : Japanese
Service kind                   : Complete Main
Default                        : No
Forced                         : No
```

Also a separate issue, but some videos don't work on said Chromium at all, but work on Edge and vice versa (say, .mkv, AVC video and E-AC3 audio). This time without any specific errors, saying only `There was an error loading the video file`, what can I do about it or what to look at?

**Comment by soameshi** [comment]
Yikes, kinda wish I found this bug earlier. This is a problem with ffmpeg.wasm, and there's not much I can do about it. The library crashes whenever I throw a file that's >2GB at it, even if I use their demo at https://ffmpegwasm.github.io/#demo. I'm also not entirely sure it's the library's fault, since this might just be a browser limitation when trying to read files that big off of disk. I might put a case in their github later if I can figure that out. If you can find a release with a smaller file size for this show, I'd recommend using that for now.

As for Chromium vs Edge differences, I haven't actually ran into them, since all shows I've gotten off of nyaa kinda just work when I throw them at the player. If I put in the file before the torrent's finished, I'll get the "There was an error loading the video file", but that's about it. I admittedly don't watch live action though, so I'm not surprised there's edge cases where the codec support differs.

**Comment by soameshi** [comment]
https://github.com/ffmpegwasm/ffmpeg.wasm#what-is-the-maximum-size-of-input-file

Yeah, this is a browser limitation, which is kinda the big flaw that always comes back to bite me with animebook. The max file size might get increased to 4GB in the future, but we're kinda just stuck with 2GB for now. Most I can do is make the error message better, which I'll try to do later.

**Comment by SpasiboKojima** [comment]
Aw shit, got it, thank you for the reply, weird that the show plays perfectly and it's just the cards creating that throws errors
Yeah most of stuff I get from nyaa works as well, except for Pokemon, both old and new, they are all old and simple, somehow only Edge can handle them ¯\_(ツ)_/¯

**Comment by soameshi** [comment]
Currently experimenting with manually increasing the limit to 4GB since it looks like wasm already supports up to 4GB since last year. https://v8.dev/blog/4gb-wasm-memory. I think ffmpeg.wasm just isn't built to take advantage of it yet. Either that or I'll find out I'm missing something when I try to rebuild it.

There's also a WORKERFS option in emscripten that supposedly allows you to access files on the hard drive without needing to load them entirely in memory, but the documentation on it is kinda shakey and some of the issues on emscripten github note that it's really slow. I don't really have high hopes for it but if it does what it claims to I might be able to get past the 4GB limit too.
https://emscripten.org/docs/api_reference/Filesystem-API.html#workerfs
Example application using it: https://stackoverflow.com/a/59138138

**Comment by soameshi** [comment]
Update: I finally got a WORKERFS prototype working, and I'm not seeing any slowness with it yet (in fact, it seems faster in some cases since you don't need to load the video file into memory) so I'm going to pursue that route to fix this. It requires me to re-architect a ton of the extension though, so testing it will take a while.

I also technically tried increasing the memory limit to 4GB, but that didn't work and also, I realized it's mostly bad in the first place to have to load an entire video file into memory.

**Comment by SpasiboKojima** [comment]
Sounds damn promising! Thanks for the effort, and I'm getting used to converting huge stuff to sub 2GB files

**Comment by soameshi** [comment]
For now if you want to try it out, you can:
- Download the repo
- Open the extensions page in chromium
- Enable developer mode
- Click 'Load unpacked'
- Select the 'extension' folder from the animebook repo you just downloaded

Reason I suggest this is cause I'm gonna have to hold off on publishing the update to everyone for another reason. To get past the 2GB limit, I'm taking advantage of a feature that Chromium might accidentally break in a month due to security fixes in the browser, and there's no workaround for chrome extensions.
https://bugs.chromium.org/p/chromium/issues/detail?id=1184892
The direction they plan on going with here suggests that they'll make an exception for extensions since they didn't realize it would be a problem, but I'm gonna watch the thread just to be safe (I'd hate to publish this update for it to break everyone in May).

**Comment by SpasiboKojima** [comment]
Worked like a charm! Thanks a lot, you are the best. Won't be updating Chromium then, gotcha

**Comment by soameshi** [comment]
Pushed update to the Chrome Web Store. Based on the commits on that chromium case and my playing around with a nightly build of chromium, it shouldn't be an issue. Only really noticed it cause I kept getting warnings about it in the Chrome console, but those went away too when I used the nightly build.
