### ISSUE TITLE
A Semi-Auto Subtitle Retimer?

### ISSUE THREAD

**Issue by TyoCre** [animebook/animebook.github.io#29]
I was wondering if a semi-auto subtitle retimer is possible, I imagine the workflow to be something like this: 
1. Pause just before the subtitle line starts
2. Click the corresponding subtitle line while holding some key.
3. The subtitle is automatically retimed so that the chosen subtitle appears at the current time.

**Comment by soameshi** [comment]
Is this not what the "Offset Subtitles" button does? A bit different than what you're describing since it demands you stop _after_ the subtitle line ends (I find this easier to pause on), but it's definitely there.

https://user-images.githubusercontent.com/20632064/113357708-a9536f80-9301-11eb-88a4-c949305398ee.mp4

**Comment by TyoCre** [comment]
Wow I feel utterly stupid, have been using animebook for months and did not realize that it was a button, not just text. Could you make it more obvious? Or maybe just hint at it in the info page on the bottom right? It might not be that often, but sometimes idiots like me exists, and it would have saved me a tremendous amount of time. 

ありがとうございます。

**Comment by soameshi** [comment]
Ah, sorry about that then! I might consider adding something later.
