### ISSUE TITLE
Longer file not working

### ISSUE THREAD

**Issue by FirionHope** [animebook/animebook.github.io#3]
Not sure if longer files dont work or specifically the one I have doesn't work, but I was trying to watch Card Captor Sakura movie 1 and its only playing the the sound, the screen is blank. Additionally the video player looks different https://i.imgur.com/OHVvdeU.png the file I have is in mkv format

**Comment by lunatum** [comment]
Was it this release? https://nyaa.si/view/1229495. I downloaded it and got the same issue as you. The problem is this video uses HEVC, which no browsers support due to licensing issues with the video format (except Edge, which can play it with some features enabled). The reason you're getting a weird video player is because the audio in that video file is supported in Chrome, so Chrome is trying to be nice by showing an "audio only" player instead.

To fix this you'll either need to find a H.264 release instead, convert the video to H.264 using something like ffmpeg, or you can install the new Microsoft Edge based on Chromium and enable HEVC support for it. If you want to try Edge (which also supports yomichan), I updated the README with more info here https://github.com/animebook/animebook.github.io#video-format-support.

**Comment by FirionHope** [comment]
Oh thanks very much, interesting stuff! I'll find a different release or something then, good to know though.
