### ISSUE TITLE
Certain videos not working with Chromium Woolyss all-codecs+ 

### ISSUE THREAD

**Issue by msw93** [animebook/animebook.github.io#35]
Not sure if this is the right place for this kind of issue. But certain video files are not loading even with Chromium Woolyss all-codecs+ .  Was able to reproduce on a different machine. Maybe I should bring this to the chromium team?

Not sure if I can post video source here.

![image](https://user-images.githubusercontent.com/4367703/133949464-c3401e52-ff2b-4372-8da5-e608dec09a0e.png)
![image](https://user-images.githubusercontent.com/4367703/133949532-5c616acd-1e39-422a-9a95-f9e0a2b8ab66.png)

**Comment by soameshi** [comment]
I've noticed this issue show up with a few anime releases lately, and looking into it I realized there's an error message from Chromium I should be showing when this happens, so I added it to the page.
![image](https://user-images.githubusercontent.com/20632064/133962778-0e52a60a-b38b-450f-9ee9-ca84c9ea5a94.png)

```
DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed
```
Can you try loading the video again? I want to see what error you get.

**Comment by soameshi** [comment]
Also fwiw, there is an in progress Chromium bug that deals with the error message I have about "audio decoder initialization failed"
https://bugs.chromium.org/p/chromium/issues/detail?id=1245123
Not sure if it's related since it's about AAC audio while my video uses EAC3, but it hints to me that there's activity around audio playback in Chromium right now.

**Comment by msw93** [comment]
Thanks for adding the error msg,

I am getting the same error as you! 

![image](https://user-images.githubusercontent.com/4367703/134035701-b911b2f6-032b-4430-ae4e-620d3dc0d788.png)

**Comment by soameshi** [comment]
So, my conclusion after playing around with this is that Woolyss Chromium doesn't like AC3 audio. I started using some other video files, and none of them work if they use AC3. I was convinced this was maybe a regression in Chromium for a second, but I decided to look at the all-codecs+ description on the woolyss site, and it doesn't actually mention AC3 as being supported.
![image](https://user-images.githubusercontent.com/20632064/134041243-ad25ce67-155b-4896-bd44-5d1ffa0ed33c.png)
Meaning, what I thought was supported is not, and since anime releases don't use AC3 that often, I conveniently never encountered this until recently. I'll work on updating the README with this, but the answer for now should be to avoid anime releases that use AC3 audio if you can.

Also to note, https://killergerbah.github.io/asbplayer/ plays the video files fine, but the audio is all muted. It probably gets away with this by ignoring the error and playing the file anyway.

**Comment by msw93** [comment]
I see! Thanks for looking into this! 

I probably shouldn't hold my breath for this to be added? 😅 

Does the chromium github have a section for feature reqs?

**Comment by soameshi** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=611517
Case has been around for 5 years, so I wouldn't hold out on it, yeah.

**Comment by msw93** [comment]
Played around with some stuff last night. Converting the audio to aac makes the videos play! 👍 

I used this [superuser answer](https://superuser.com/a/1348348), I had to tinker with the ffmpeg installation and the script options, but it works really well, one click and you can batch convert all videos in a folder. Takes only a minute or so per show!

I think this is a good solution for Windows users, but might be a touch high level to set up 😂
