### ISSUE TITLE
I can't find any all-codecs+ download available

### ISSUE THREAD

**Issue by avc1657** [animebook/animebook.github.io#36]
Yo, guys, could anyone please upload an all-codecs+ version of chromium to some website then provide the link? I can't find any all-codecs+ version to download: https://imgur.com/a/fAX5XNX

Thanks in advance.

**Comment by soameshi** [comment]
I ran into this too when my ungoogled chromium auto-updated. Still looking into why this happened, but navigating to the flag chrome://flags/#enable-clear-hevc-for-testing and enabling it seems to get it working again.

**Comment by soameshi** [comment]
Yeah, I'm just seeing things. Tried comparing the 2 Chromiums and they're basically the same
https://screenshotcomparison.com/comparison/18132
https://screenshotcomparison.com/comparison/18135

^The above site lets you compare 2 images. When you hover your mouse over image 1, it's swaps it out for image 2. But because both images are completely the same, I don't see a difference. So, that's a relief. I'll update the README.
