### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Geniusssmit** [animebook/animebook.github.io#4]
Hey, love your site!
Can you add shortcut for rewinding/skipping 87 seconds? most of anime openings and endings are 90 secs, I used it for I while on offline players. For example ctrl+< and ctrl+> would be great

**Comment by lunatum** [comment]
I'll think about it. I'd use the feature, but I'm not super excited to use up a hotkey for something so specific. And if I did a generic thing like mpv does where you can do a big jump of 60 seconds forward/backward, it's not useful. 90 also is bad, since you need to verify the last few moments of the OP to make sure you didn't skip anything important. Might be best to just Abandon The Nice Round Numbers when it comes to stuff like this. Specially since the site's name is animebook.

**Comment by Geniusssmit** [comment]
I used it all the time, you see opening you press 1 button you see the show basically
