### ISSUE TITLE
ffmpeg not starting

### ISSUE THREAD

**Issue by linkup89** [animebook/animebook.github.io#40]
Getting this error whenever I try to open a video file. This only happens when the extension is on.

Failed to prepare video for anki export: ffmpeg didn't start: WebAssembly.Memory(): could not allocate memory

Error: ffmpeg didn't start: WebAssembly.Memory(): could not allocate memory
    at FFmpeg.createCore (chrome-extension://ohcbgkombhgcbjcikjlgdmjkpibafppa/bg/js/ffmpeg.js:52:19)
    at FFmpeg.load (chrome-extension://ohcbgkombhgcbjcikjlgdmjkpibafppa/bg/js/ffmpeg.js:60:38)
    at handleMessage (chrome-extension://ohcbgkombhgcbjcikjlgdmjkpibafppa/bg/js/ffmpeg_worker.js:17:33)
    at onmessage (chrome-extension://ohcbgkombhgcbjcikjlgdmjkpibafppa/bg/js/ffmpeg_worker.js:32:5)

![image](https://user-images.githubusercontent.com/1606897/146007763-9bff95b3-f10d-4e78-ae05-abc3b78b7f80.png)

**Comment by soameshi** [comment]
Yeah, it's the extension failing, so it'll only prevent you from making flashcards.

This one's puzzling me though, since I can't reproduce it on my machine. Based on the error message, my initial instinct is to ask how much RAM your machine has available, though I'm not sure that would be the issue. It's failing to start the WebAssembly version of ffmpeg (what I use to record flashcards), but that shouldn't be memory intensive at all. It's also failing before it even tries to load your video, so it likely has nothing to do with what video you use.

I'm hoping it's not a chrome flag set wrong (e.g. something to do with WebAssembly), but you could probably test that by trying it out on a clean browser. What browser are you using by the way?

**Comment by linkup89** [comment]
I have 64gb of ram.
Actually I was using the latest 32 bit of chrome.
I changed to the 64 bit version and this is not happening anymore :).
Maybe this is the underlying issue https://v8.dev/blog/4gb-wasm-memory ??

**Comment by soameshi** [comment]
Looks like other people are dealing with this too.
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/228

The default ffmpeg.wasm build specifies INITIAL_MEMORY at 2GB, so I'd say that's too big for 32-bit applications. Also, the project just wants 2GB available to load large videos into memory, so I think it'd be more idiomatic to specify INITIAL_MEMORY small and set ALLOW_MEMORY_GROWTH, MAXIMUM_MEMORY appropriately in the emscripten build so it can grow to 2GB. Since I'm already building my own version of ffmpeg.wasm (https://github.com/animebook/ffmpeg.wasm-core), I can look into changing that.

Regardless, I'm reading videos off disk (not loading them into memory) so I shouldn't need the 2GB anyway.

**Comment by soamsy** [comment]
Updated the ffmpeg memory settings. If you happen to go back to 32-bit Chrome for any reason, let me know if breaks again.
