### ISSUE TITLE
[Feature request] Highlighted subtitles from a user defined list.

### ISSUE THREAD

**Issue by mpPie** [animebook/animebook.github.io#56]
This idea comes from the "Language Reactor" addon and would be used for language learning.

The idea is to highlight all the words in one color, as to mark them as "unknown". While watching the episode, words can be manually recolored, to mark them with different meanings ("learning" and "learned" as an example).

Thank you for Animebook.

**Comment by soamsy** [comment]
Sorry for the late response, but since animebook is focused on integration with Anki/Yomichan, I recommend using those tools to figure out what words you've already mined. Those tools are much better at this than anything I could pull off with the player.　For example, if I highlight a word and it's already mined, I can click the book icon in Yomichan to see exactly where I mined it from, with context and everything.
![brave_2022-08-16_21-29-16](https://user-images.githubusercontent.com/20632064/185028896-31c07272-37e1-42a8-8ebd-a50c08e195b2.jpg)

![anki_2022-08-16_21-31-26](https://user-images.githubusercontent.com/20632064/185028872-c8045e1e-3480-4988-92c0-2f8cae2311c9.jpg)

And if your concern is checkmarking _everything everything_ you've learned regardless of whether you've mined it or not, I think you're going to be in a lot of pain as it rings a lot of the old mining strategy of converting entire libraries of anime/shows into flashcards (I've seen people amass 10s of thousands this way), and then manually deleting all the cards you already know. From my experience it is a painstaking task to try to encode your brain's knowledge into some software's dictionary, only for you to come across another カメラ or another アニメ that you have to mark as "known", cause the software doesn't know what's obvious to you.

And from the technical side, I don't want animebook to have parse Japanese text into "word" chunks, since that's a very hard problem to solve for Japanese, especially when words are often written in different ways (kanji, kana, mazegaki, etc.). The better test on whether it's "learned" is whether you can read it or not anyway.
