### ISSUE TITLE
Export Retimed Subs

### ISSUE THREAD

**Issue by xrishox** [animebook/animebook.github.io#6]
I'm not sure if this is something that browsers are capable of doing, or if it is outside the scope of this project, but being able to export or replace subs that are retimed when you watch them would be a nice feature since then they would be permanently fixed rather than temporarily fixed. Seeing as how most japanese subs have notoriously bad timings, if as someone works their way through watching a show timed on animebook they could just easily fix the subs these could easily be re-uploaded to kitsunekko drastically reducing this problem.

if I'm going to be watching a mountain of untimed anime, I might as well fix it and re-upload while i'm at it. that said i don't care nearly enough to download an external tool and do it manually for each episode I watch. that said if there was just an export button that would make it easy enough to justify doing it.

**Comment by lunatum** [comment]
Probably possible, but animebook isn't suited for this. It only offsets by a static amount, so if timing is more messed up than that e.g. you need a  3 second offset before the OP, and a 13 second offset after, then exporting isn't useful anyway. Plus, since the site supports .srt, .ass, and .vtt, I'd need to support all 3 as a potential export format depending on which one you uploaded, which just sounds complicated. Especially when it comes to .ass files, which animebook drastically simplifies when displaying. For example, an .ass file might have crazy colored fonts and karaoke, which you can't see in animebook (you just see text), so it's not exactly a good environment for editing the subtitles in the first place. You don't want to be editing something you can't see. Also, animebook would only be able to edit 1 episode at a time, which sounds awkward to me, since you're usually interested in fixing an entire series.

I say to leave this job to the tools designed for it e.g. Aegisub or Alass. The static offset is really just to mimic a similar feature in mpv.

**Comment by xrishox** [comment]
> so if timing is more messed up than that e.g. you need a 3 second offset before the OP, and a 13 second offset after, then exporting isn't useful anyway.

This is true, but many subs aren't broken in this way. Many just need a one off offset to fix it entirely.

>Also, animebook would only be able to edit 1 episode at a time, which sounds awkward to me, since you're usually interested in fixing an entire series.

I mean I would suggest that's exactly why it's such a good fit. If I go through and watch a full episode of a show then  I know for sure that the subtitles are correct. Obviously this isn't good for an automated push it in and spit it out option, but in my experience with stuff like alass, those tools aren't very good anyways. You say 1 at a time like this is something I would be going out of my way to do. I'm going to be watching the series anyways.

I'll give you one such example where this would be a huge boon. I'm planning on going through and watching one piece once I'm done with my current show as part of my immersion. Now I've jumped around to a couple of episodes hundreds of episodes apart and they all need like a substantial offset (on the order of like 75-95 seconds but it varies) due to stuff like the toei lead-in on horriblesubs. It is like such a bad offset that I could see someone actually thinking the subs were downright wrong or broken. That said the offset doesn't ever appear to change as the episode goes on, so a single offset restructuring fixes it entirely. Running it through alass breaks it completely. I'm not particularly interested in downloading an external tool to manually fix every single episode, but the way I see it if it was built into the player and i'm going to be watching hundreds of episodes of one piece anyways, it would be really useful to the greater community if I could just offset on each individual episode as I'm watching the series and spit out fixed subtitles to upload to kitsunekko that it would be a good thing.

To be clear this is your project and I'm super grateful that it exists at all, so don't consider this any sort of a demand. I just think that it could be a simple, low friction way for people to increase the overall quality of subs available. Either way if you don't think this is a fit for the project (or you don't want to do it) you can feel free to close the issue.

**Comment by lunatum** [comment]
Yeah, I'm still not convinced. I could maybe see it saving you some time if you're interested in fixing something like One Piece, but that show's still the simple case, where the offset works for it (for many shows it does not). And if an offset does work, it's not really a big deal to open the file in Aegisub and hit Timing > Shift Times... if you must fix it. If you don't need to fix it, then I wouldn't worry about it. Fixing One Piece is a huge undertaking anyway, so you're still going to need dedication to regularly download a file every episode you watch (not to mention to watch every episode; there's a lot of filler).

I'm also not sure I would even trust a subtitles file spit out by animebook. The tool invites you to retime the subs in realtime as you watch a show e.g. offset by 10 seconds pre-OP, then by 5 seconds after the OP, and I could see myself exporting at the end without realizing the offset doesn't work. You don't really have an overall picture of what's happening like you do in Aegisub. And the "Offset Subtitles" button isn't super accurate in the first place, in part due to browser limitations, since it'll give you offsets like 4.86, 5.08, inviting you to ignore that there's probably a perfect offset of 5 seconds exact if you don't realize it. From my standpoint, the feature's limitations really overshadow the small time savings you might get from it.
