### ISSUE TITLE
Hiding Parenthesis Sometimes Leaves Behind 1 )

### ISSUE THREAD

**Issue by cademcniven** [animebook/animebook.github.io#66]
I had the following subtitle lines:
![chrome_elvHa1Te1q](https://user-images.githubusercontent.com/17060136/197091830-1e8d2b51-5e1e-424c-813b-e0667969649c.png)

which produced the following result when pressing h to hide parenthesis:

![chrome_omz7txddbi](https://user-images.githubusercontent.com/17060136/197091895-49d6ba0c-1729-4e5f-891c-9f7462c1f7ce.png)

**Comment by soamsy** [comment]
Personally forgot that double parentheses show up sometimes, but this can be fixed by having the regex pattern `\(\(.*?\)\)` at the top of the regex replacements for hiding parentheses
![image](https://user-images.githubusercontent.com/20632064/197094126-6189ad2d-2076-416d-81ae-764c1d2f57e0.png)

And since that seems like a good idea, I made it the default. If you want the new default, you'll need to either delete your browser's local storage for animebook.github.io, or you can manually change the regex on the appearance tab. The new regex does need to be at the top however.

**Comment by soamsy** [comment]
Also I'm not sure why ((僕もお父さんみたいに強くなるんだ！)) didn't hide at all, but maybe it has something to do with the subtitle file you're using. If you're still having issues let me know.
