### ISSUE TITLE
[Issue] Typing "-" in offset box shrinks subtitles

### ISSUE THREAD

**Issue by temccarthy** [animebook/animebook.github.io#69]
Typing "-" in offset the subtitles should make the offset a negative number. My solution right now is to hit the decrement arrow to get to my desired offset but it would be much easier if "-" in the offset box just made the number negative

**Comment by soamsy** [comment]
Huh, I thought this was fixed in https://github.com/animebook/animebook.github.io/commit/d1dc77903385b3e969e0393a8fc24c76d9d704d7 a few days ago, and typing "-" works for me now. Maybe the bugged version of the site is still cached for you? (which would be weird since Github should be invalidating any caching on update)

**Comment by temccarthy** [comment]
Yeah I just had to refresh the page and that solved the issue. Thanks!
