### ISSUE TITLE
Support automatic export to Anki flashcards

### ISSUE THREAD

**Issue by soameshi** [animebook/animebook.github.io#8]
https://www.youtube.com/watch?v=M4t7HYS73ZQ
I recently saw this workflow for making anime cards in mpv, and I think it'd be awesome to have in animebook too. The idea would be similar, in that you'd select some text from captions in the sidebar, hit a hotkey, and have the image + audio + sentence sent to your card in anki.

*Implementation Ideas*
To get this working, going through AnkiConnect is how it should be done. However, the way AnkiConnect works is it hosts a server on localhost, which a webpage cannot make requests to for security reasons. So, I'm pretty sure I'd need to make a browser extension to get around this limitation, which is how Yomichan does it. I'm not too excited to ask everyone to download an extension to use this feature, but it looks like the easiest path forward. Other options would be to have everyone download animebook and host it locally on a port like localhost:3000 (not happening), or making animebook an electron app that you download which, removes all benefits that distinguish animebook from something like voracious. Note: voracious works by making a call to the ffmpeg exe on your operating system, which brings me to another problem.

To get this automatic, I have to use ffmpeg. But, a browser extension can't use an exe/binary from the operating system directly, which I thought would stop me in my tracks right there with this, but looking around ffmpeg resources it turns out there's a WebAssembly version of it I can use for javascript projects: https://github.com/ffmpegwasm/ffmpeg.wasm. I experimented with it a bit, and all you do is send the video file to it from javascript and you can run any ffmpeg command on it to get ouput audio/video/etc. It's pretty cool. Only downside is that it would bump the size of this would-be extension by ~25mb, but that seems fine by me.

I'd also need some sort of configuration page like yomichan's to tell the extension what fields should be updated in Anki. Doesn't need to be too complicated, so I'll probably just model it after the Yomichan config page. 
- I want some options on whether to replace, append, or prepend to existing content on an anki field, for example if you want to append sentence audio to an existing word audio field, rather than overwrite it.
- I also want an option on whether to include newlines in the exported sentence or not, since some people have to manually delete those.

**Comment by chalkmurex** [comment]
Update: I got a proof of concept working, but it's slower than the script in the YouTube video. When I try to upload a flashcard to anki it takes
- ~2 seconds to record audio and image with ffmpeg.wasm
- ~3 seconds to upload the audio and image through AnkiConnect

The lua script in the video gets around the AnkiConnect slowness by sending the file directly to your anki media folder, which I can't do. Not sure why AnkiConnect is so slow honestly. I might need to dig into the project a little to find out.

Also my ffmpeg command for images is kinda slow in the browser. It might be better to not use ffmpeg for that and instead use the video -> canvas trick I do for the screenshot hotkey, granted that is Chrome only (though to be honest I doubt anyone uses the site with Firefox due to the poor video support).

**Comment by chalkmurex** [comment]
Blocked at the moment since the ffmpeg wasm library repeatedly loads itself into memory every time I record a flashcard, causing the browser to crash due to an out-of-memory error. There are a couple issues on the github about it, but no cause has been found yet (or at least talked about). I might be able to contribute, since it seems like ffmpeg is spawning web workers every time you run a command and never releasing them, but that might just be how emscripten does things? Not sure. I might also look into a different library, but I'm not sure how slow that'll be compared to my times up above.

**Comment by Shibasaki175** [comment]
I tried to play the video on the animebook and mpv at the same time. It is possible to copy the sentence on the animebook and create the card by pasting it on the mpv, but sometimes it does not copy the audio correctly, due to some small differences in the subtitles between the two.

**Comment by xrishox** [comment]
Wow if you could get something like this implemented that would be amazing. You may want to consider looking into how the migaku addon does things. Maybe that could offer you a decent solution since they already allow for making cards from a browser extension using ankiconnect. They appear to have a somewhat robust setup other than the fact that they make sentence cards instead of "anime cards". I think they are also using a forked version of ankiconnect though and they have a bunch of other nonsense for integrating their other tools. I'm not sure if the way they do things are dependent on those other tools and thus not possible for you. It is worth noting though, that whatever he is doing does require ffmpeg to be installed on the os.

**Comment by soameshi** [comment]
Sorry for the lack of responses; I stopped work on this because of the issue I had with ffmpeg wasm, but it turns out the bug I was running into was fixed in a recent release of theirs, so I decided to try it again. 

Long story short, I got it working well enough that I want other people to try it now. The workflow is mostly how you describe it. You add a card using Yomichan and then you add context using Animebook. Not much more to it than that, but that's all I really need.

https://user-images.githubusercontent.com/20632064/106185971-d8fac580-6160-11eb-9ef0-b3b898150156.mp4

**Comment by soameshi** [comment]
> whatever he is doing does require ffmpeg to be installed on the os
Huh, I thought about that approach, but ffmpeg wasm mostly does everything I need it to while being contained in the extension. The only big downside is that is has less codecs than an actual install of ffmpeg, so I can't do certain things like export to webp, but I can live without.

To be honest, I'd like to try out the Migaku player if it's ever publicly released, since Yoga seems to have a lot more going into it than I can put into animebook. I was also under the impression he liked vocab cards for objects and other non-abstract nouns, so I'd be surprised if you couldn't make them with his tools.

**Comment by xrishox** [comment]
i got it installed on brave (since that is my immersion browser), and inside of the settings it seems to pick up my anki stuff like deck names and things, but when I hit the + to add stuff to the card inside of the video page it says

>Could not find Anki server. Please make sure Anki is running and AnkiConnect is installed.

Anki connect should be working properly since the settings picks up my decks and yomichan can make cards just fine. I wonder what could be causing issues.

While yoga has a lot of good ideas I tend to avoid his stuff since it appears to be in a perpetual alpha state. It might be nice to look at to get ideas or see how he does things but beyond that I don't know.

**Comment by xrishox** [comment]
weird i set it up in chrome and everything seems to be working properly. I'm not sure if it's a bug in brave or it's just due to my setup on brave being kind of janky. redoing my entire setup in chrome from scratch might have just avoided some mistakes i made in my brave setup. either way it appears to be working and that's great!

**Comment by soameshi** [comment]
Hmm, kinda concerning that it failed when adding cards like that. It might have to do with the extension's permissions, but I'm glad you got it working. And fwiw I use the all-codecs+ builds of Chromium from https://chromium.woolyss.com.

Leaving this case open for now while I test things out.

**Comment by xrishox** [comment]
unless it's something you are ocd about fixing i wouldn't really worry about it for me. i was just using brave as an arbitrary immersion browser. i'm fine with changing it with another chromium based browser. i'm currently using chrome now, but will probably switch to the all codec version of chromium you linked to... though does it automatically update itself?

**Comment by soameshi** [comment]
It seems to have its own updater when you start it (at least on Windows). Just be sure to use the all-codecs+ version (with the plus sign) and it should play whatever video you throw at it. I updated the README with info about it.

**Comment by soameshi** [comment]
Extension is now on the Chrome Web Store. https://chrome.google.com/webstore/detail/animebook-anki-export/ohcbgkombhgcbjcikjlgdmjkpibafppa
