### ISSUE TITLE
enhancement: favorite function

### ISSUE THREAD

**Issue by KamiGim** [animebook/animebook.github.io#9]
It would be good, if we can favorite sentences, so that I can mass import into anki later.

**Comment by chalkmurex** [comment]
Nah, I don't want to support this workflow. Why press a favorite button when you could just press the "add to anki" button in yomichan instead? That way you don't have to bother crawling over the show again to make cards. If this is about not wanting to take screenshots + record audio until you're done with the show, I'd rather work on something like #8 instead of this (idk how far #8 will pan out though, but even if it doesn't I still don't want this feature)
